### ISSUE TITLE
How to use as a client

### ISSUE THREAD

**Issue by tunage** [ParallelMazen/pusherpp#2]
I installed your software and everything compiled and I achieved an error code 200 OK on a test connection.
But, I would like to be able to connect to this APP_KEY as a client -> https://www.cryptsy.com/pages/pushapi  which appears to have a similar authentication setup though the Javascript client does use a different server/ip/service (JSON and not socket).

I replaced Their APP_KEY with mine and I get 'unauthorized'. I tried NULL and "0" for APP_ID and APP_SECRET and still get 'unauthorized'.

Is it possible to receive public pusher updates from another Pusher user?

**Comment by inparallel** [comment]
Hi, (3 years later), this library is not intended to be used as a client. You can use the following instead:
https://github.com/niv/pusher-websocket-cpp
